# Production API Configuration - Generated by Terraform
VITE_API_BASE_URL=${api_base_url}
VITE_CLOUDFRONT_DOMAIN=${cloudfront_domain}
VITE_NODE_ENV=${node_env}
VITE_ENABLE_DEBUG=${enable_debug}
VITE_AWS_REGION=${aws_region}
